services:
  api_gestao_eventos:
    container_name: gestao-eventos-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg_gestao_eventos
    command: bash -c "yarn migration:run && yarn dev"

  pg_gestao_eventos:
    container_name: gestao-eventos-database
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5434:5432
